#### Contents

This repository contains the files for Coursera's Exploratory Data Analysis Course Project 1. In addition to this file, there are four R script files and four PNG files that contain the plots created by the scripts. The files from the original repo are contained in the file labelled "original."

To run any of the scripts, you must first download the data from:

https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip

and have it unzipped into your working directory.

#### About the data

This assignment uses data from the UC Irvine Machine Learning Repository, a popular repository for machine learning datasets. In particular, it uses the "Individual household electric power consumption Data Set," described as measurements of electric power consumption in one household with a one-minute sampling rate over a period of almost 4 years. Different electrical quantities and some sub-metering values are available. 

The following descriptions of the nine variables in the dataset are taken from the UCI website:

- **Date**: Date in format dd/mm/yyyy
- **Time**: time in format hh:mm:ss
- **Global_active_power**: household global minute-averaged active power (in kilowatt)
- **Global_reactive_power**: household global minute-averaged reactive power (in kilowatt)
- **Voltage**: minute-averaged voltage (in volt)
- **Global_intensity**: household global minute-averaged current intensity (in ampere)
- **Sub_metering_1**: energy sub-metering No. 1 (in watt-hour of active energy). It corresponds to the kitchen, containing mainly a dishwasher, an oven and a microwave (hot plates are not electric but gas powered).
- **Sub_metering_2**: energy sub-metering No. 2 (in watt-hour of active energy). It corresponds to the laundry room, containing a washing-machine, a tumble-drier, a refrigerator and a light.
- **Sub_metering_3**: energy sub-metering No. 3 (in watt-hour of active energy). It corresponds to an electric water-heater and an air-conditioner.

#### Acknowledgements
I would like to thank the many students and CTAs on the Coursera class forums for Exploratory Data Analysis whose questions and answers provided an invaluable resource in the completion of this project. Certain descriptions of the original data and the variables are taken from the UCI website and the Coursera project description.
